// Copyright (C) 2020  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details, at
// https://fpgasoftware.intel.com/eula.


// Generated by Quartus Prime Version 20.1 (Build Build 720 11/11/2020)
// Created on Sun Dec 05 17:53:21 2021

two2onemux two2onemux_inst
(
	.SELECT(SELECT_sig) ,	// input  SELECT_sig
	.A(A_sig) ,	// input [N-1:0] A_sig
	.B(B_sig) ,	// input [N-1:0] B_sig
	.y(y_sig) 	// output [N-1:0] y_sig
);

defparam two2onemux_inst.N = 4;
