// Copyright (C) 2020  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details, at
// https://fpgasoftware.intel.com/eula.


// Generated by Quartus Prime Version 20.1 (Build Build 720 11/11/2020)
// Created on Tue Nov 02 23:20:10 2021

OnOffToggle OnOffToggle_inst
(
	.OnOff(OnOff_sig) ,	// input  OnOff_sig
	.IN(IN_sig) ,	// input  IN_sig
	.OUT(OUT_sig) 	// output  OUT_sig
);

defparam OnOffToggle_inst.ON = 'b1;
defparam OnOffToggle_inst.OFF = 'b0;
